version: '3.9'

services:
  app:
    build: .
    container_name: dictionary-api
    restart: always
    ports:
      - 5000:5000
    networks:
      - api
    volumes:
      - ./src:/usr/src/app
  mysql:
    image: mariadb:latest
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    networks:
      - api
    volumes:
      - db_data:/var/lib/mysql

networks:
  api:
    driver: bridge

volumes:
  db_data: {}